version: "3.8"

services:
  rtmp-server:
    build:
      context: nginx
      dockerfile: Dockerfile
      target: runtime-image
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
      - "1935:1935"
